(define (problem Monster3)

    (:domain gameDomain)
    
    (:objects loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 treasure4 treasure8 bow spear magic_shoes6 gameHero)
    
    (:init
        (cave loc1)
        (cave loc2)
        (cave loc3)
        (cave loc4)
        (cave loc5)
        (cave loc6)
        (cave loc7)
        (cave loc8)
        (cave loc9)
        (hero gameHero)
        (hero_at gameHero loc1)
        (monster_at loc3)
        (monster_at loc5)
        (pit_at loc7)
        (treasure treasure4)
        (treasure_at treasure4 loc4)
        (treasure treasure8)
        (treasure_at treasure8 loc8)
        (weapon bow)
        (weapon_at bow loc4)
        (weapon spear)
        (weapon_at spear loc2)
        (magic_shoes magic_shoes6)
        (magic_shoes_at magic_shoes6 loc6)
        (leads_to loc1 loc2)
        (leads_to loc1 loc5)
        (leads_to loc2 loc1)
        (leads_to loc2 loc3)
        (leads_to loc3 loc2)
        (leads_to loc3 loc4)
        (leads_to loc4 loc3)
        (leads_to loc5 loc2)
        (leads_to loc5 loc9)
        (leads_to loc5 loc6)
        (leads_to loc5 loc7)
        (leads_to loc6 loc5)
        (leads_to loc6 loc8)
        (leads_to loc7 loc4)
        (leads_to loc8 loc7)
    )
    
    (:goal (and (hero_at gameHero loc1) (hasTreasure gameHero treasure4)  (hasTreasure gameHero treasure8)))
    
)
